/* for ERROR */
export const ERROR_SHOW = "ERRORS/ERROR_SHOW"
export const ERROR_HIDE = "ERRORS/ERROR_SHOW"
/* for USER */
export const LOGIN_REQUEST = "USER/LOGIN_REQUEST"
export const LOGIN_SUCCESS = "USER/LOGIN_SUCCESS"
export const LOGIN_ERROR = "USER/LOGIN_ERROR"

export const LOGOUT_REQUEST = "USER/LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "USER/LOGOUT_SUCCESS"
export const LOGOUT_ERROR = "USER/LOGOUT_ERROR"